Models/ErrorViewModel.cs
namespace controle_de_pontos_mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using controle_de_pontos_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace controle_de_pontos_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/JuntosController.cs
using Microsoft.AspNetCore.Mvc;

namespace controle_de_pontos_mvc.Controllers
{
    public class JuntosController : Controller
    {
        public IActionResult JuntosDispesas()
        {
            return View();
        }
    }
}

Controllers/LekaController.cs
using Microsoft.AspNetCore.Mvc;

namespace controle_de_pontos_mvc.Controllers
{
    public class LekaController : Controller
    {
        public IActionResult LekaDispesas()
        {
            return View();
        }

    }
}

Controllers/LunaController.cs
using Microsoft.AspNetCore.Mvc;

namespace controle_de_pontos_mvc.Controllers
{
    public class LunaController : Controller
    {
        public IActionResult LunaDispesas()
        {
            return View();
        }
    }
}

Controllers/MarcoController.cs
using Microsoft.AspNetCore.Mvc;
using controle_de_pontos_mvc.Models;
using System.Diagnostics;


namespace controle_de_pontos_mvc.Controllers
{
    public class MarcoController : Controller
    {
        public IActionResult MarcoDispesas()
        {

            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-5">Controle de despesas (Marco, Leka & Luluca).</h3>
        <div class="row">
 
    <div>
        <img src="https://www.pngmart.com/files/13/High-School-Anime-Couple-PNG-Transparent-Picture.png" alt="Descrição da imagem">
    </div>
</div>
</div>

Views/Juntos/JuntosDispesas.cshtml
@{
    ViewData["Title"] = "Juntos Despesas";
}

<h2>Controle de Despesas Juntos</h2>

<div class="row">
    <form>
        <div class="form-group">
            <label for="mes">Mês?</label>
            <input type="text" class="form-control" id="mes" placeholder="Digite um mês de 2024...">
        </div>
        <div class="form-group">
            <label for="valor">Quanto recebemos juntos?</label>
            <input type="text" class="form-control" id="valor" placeholder="Digite um valor em reais">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="gerarExcel">
            <label class="form-check-label" for="gerarExcel">Gerar Excel?</label>
        </div>
        <button type="submit" class="btn btn-primary">Go</button>
    </form>
</div>

Views/Leka/LekaDispesas.cshtml
@{
    ViewData["Title"] = "Leka Despesas";
}

<h2>Controle de Despesas Leka</h2>

<div class="row">
    <form>
        <div class="form-group">
            <label for="mes">Mês?</label>
            <input type="text" class="form-control" id="mes" placeholder="Janeiro...">
        </div>
        <br />

        <div class="form-group">
            <label for="valor">Quantidade de dias que você deveria ter trabalhado no mês</label>
            <input type="text" class="form-control" id="valor" placeholder="Ex: 22...">
        </div>
        <br />


        <div class="form-group">
            <label for="valor">Quantidade de plantões realizados</label>
            <input type="text" class="form-control" id="valor" placeholder="Ex: 2...">
        </div>
        <br />


        <div class="form-group">
            <label for="valor">Quantidade de faltas</label>
            <input type="text" class="form-control" id="valor" placeholder="Ex: 1">
        </div>
        <br />


        <div class="form-group">
            <label for="valor">Dessas faltas, quantas foram em plantão?</label>
            <input type="text" class="form-control" id="valor" placeholder="Ex: 0 (Nenhum)">
        </div>
        <br />


            <legend class="col-form-label col-sm-2 pt-0">Foi um mês atípico?</legend>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="opcao1" checked>
                    <label class="form-check-label" for="gridRadios1">
                        Sim
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="opcao2">
                    <label class="form-check-label" for="gridRadios2">
                        Não
                    </label>
                </div>
        
        <br />

        <div class="form-group">
            <label for="valor">Fez horas-extras/reposição?</label>
            <input type="text" class="form-control" id="valor" placeholder="Ex: Sim">
        </div>
        <br />

        <div class="form-group">
            <label for="valor">Se sim, quantas horas por dia?</label>
            <input type="text" class="form-control" id="valor" placeholder="Ex: 1,48...">
        </div>
        <br />


        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="gerarExcel">
            <label class="form-check-label" for="gerarExcel">Gerar Excel?</label>
        </div>
        <br />

        <button type="submit" class="btn btn-primary">Go</button>
    </form>
</div>

Views/Luna/LunaDispesas.cshtml
@{
    ViewData["Title"] = "Luna Despesas";
}

<h2>Controle de Despesas Luna</h2>

<div class="row">
    <form>
        <div class="form-group">
            <label for="mes">Mês?</label>
            <input type="text" class="form-control" id="mes" placeholder="Digite um mês de 2024...">
        </div>
        <div class="form-group">
            <label for="valor">Quanto recebemos juntos?</label>
            <input type="text" class="form-control" id="valor" placeholder="Digite um valor em reais">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="gerarExcel">
            <label class="form-check-label" for="gerarExcel">Gerar Excel?</label>
        </div>
        <button type="submit" class="btn btn-primary">Go</button>
    </form>
</div>

Views/Marco/MarcoDispesas.cshtml
@{
    ViewData["Title"] = "Marco Despesas";
}

<h2>Controle de Despesas Marco</h2>

<div class="row">
    <form>
        <div class="form-group">
            <label for="mes">Mês?</label>
            <input type="text" class="form-control" id="mes" placeholder="Digite um mês de 2024...">
        </div>
        <div class="form-group">
            <label for="valor">Quanto recebemos juntos?</label>
            <input type="text" class="form-control" id="valor" placeholder="Digite um valor em reais">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="gerarExcel">
            <label class="form-check-label" for="gerarExcel">Gerar Excel?</label>
        </div>
        <button type="submit" class="btn btn-primary">Go</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto de controle de despesas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/controle_de_pontos_mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leka" asp-action="LekaDispesas">Leka</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marco" asp-action="MarcoDispesas">Marco</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Luna" asp-action="LunaDispesas">Luna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Juntos" asp-action="JuntosDispesas">Juntos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>